---
apiVersion: v1
kind: Namespace
metadata:
  name: hadoop
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-conf
  namespace: hadoop
data:
  HADOOP_CONTROLLER: hadoop-controller
  HOST_NAMES: "hadoop-controller hadoop-worker-arm hadoop-worker-x86"
  #HOST_NAMES: "hadoop-controller hadoop-worker-x86"
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-jobhistory
  namespace: hadoop
spec:
  type: NodePort
  selector:
    app: hadoop-controller
  ports:
    - name: jobhistory
      port: 19888
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-controller
  namespace: hadoop
spec:
  selector:
    app: hadoop-controller
  clusterIP: None
  ports:
  - name: port-0
    port: 8030
---
apiVersion: v1
kind: Pod
metadata:
  name: hadoop-controller
  namespace: hadoop
  labels:
    app: hadoop-controller
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
    #kubernetes.io/hostname: openeuler-node5-arm64
  containers:
    - name: hadoop-master
      image: ghcr.io/liusheng/hadoop-3.3.0-openeuler:aarch64
      imagePullPolicy: Always
      resources:
        requests:
          memory: "4096Mi"
          cpu: "4096m"
      env:
        - name: HOST_NAMES
          valueFrom:
            configMapKeyRef:
              name: hadoop-conf
              key: HOST_NAMES
        - name: HADOOP_SERVICES
          value: "all"
        - name: HADOOP_CONTROLLER
          valueFrom:
            configMapKeyRef:
              name: hadoop-conf
              key: HADOOP_CONTROLLER
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-worker-arm
  namespace: hadoop
spec:
  selector:
    app: hadoop-worker-arm
  clusterIP: None
  ports:
  - name: port-1
    port: 8040
---
apiVersion: v1
kind: Pod
metadata:
    name: hadoop-worker-arm
    namespace: hadoop
    labels:
      app: hadoop-worker-arm
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
    #kubernetes.io/hostname: openeuler-node5-arm64
  containers:
    - name: hadoop-worker-arm
      image: ghcr.io/liusheng/hadoop-3.3.0-openeuler:aarch64
      imagePullPolicy: Always
      resources:
        requests:
          memory: "4096Mi"
          cpu: "4096m"
      env:
        - name: HOST_NAMES
          valueFrom:
            configMapKeyRef:
              name: hadoop-conf
              key: HOST_NAMES
        - name: HADOOP_SERVICES
          value: "worker"
        - name: HADOOP_CONTROLLER
          valueFrom:
            configMapKeyRef:
              name: hadoop-conf
              key: HADOOP_CONTROLLER
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-worker-x86
  namespace: hadoop
spec:
  selector:
    app: hadoop-worker-x86
  clusterIP: None
  ports:
  - name: port-1
    port: 8040
---
apiVersion: v1
kind: Pod
metadata:
    name: hadoop-worker-x86
    namespace: hadoop
    labels:
      app: hadoop-worker-x86
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
    #kubernetes.io/hostname: openeuler-node1-x86
  containers:
    - name: hadoop-worker-x86
      image: ghcr.io/liusheng/hadoop-3.3.0-openeuler:x86
      imagePullPolicy: Always
      resources:
        requests:
          memory: "4096Mi"
          cpu: "4096m"
      env:
        - name: HOST_NAMES
          valueFrom:
            configMapKeyRef:
              name: hadoop-conf
              key: HOST_NAMES
        - name: HADOOP_SERVICES
          value: "worker"
        - name: HADOOP_CONTROLLER
          valueFrom:
            configMapKeyRef:
              name: hadoop-conf
              key: HADOOP_CONTROLLER
  restartPolicy: Always
